/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Feedback: typeof import('./components/Feedback.vue')['default']
    Form: typeof import('./components/Form.vue')['default']
    Notify: typeof import('./components/Notify.vue')['default']
    PictureUpload: typeof import('./components/PictureUpload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
