/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Appbar: typeof import('./components/Appbar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Form: typeof import('./components/Form.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    PictureUpload: typeof import('./components/PictureUpload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
